[package]
name = "crustd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
log = "0.4"
stderrlog = "0.4"
anyhow = "1.0"
nix = "0.23.1"